### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-player-settings#17]
Per user, I can't replicate.

```Hi, I am seeing this error during a player login (in player's browser console).
Foundryvtt 11.301, dnd5e 2.2.1, player settings 11.01

monks-player-settings.js:305 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'onChange')
[Detected 1 package: monks-player-settings]
    at MonksPlayerSettings.refreshSettings (monks-player-settings.js:305:33)
    at MonksPlayerSettings.checkSettings (monks-player-settings.js:276:39)
    at MonksPlayerSettings.ready (monks-player-settings.js:57:29)
    at Object.fn (monks-player-settings.js:338:25)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8684:11)
    at async Game._initializeGameView (foundry.js:9925:5)
    at async Game.initialize (foundry.js:8588:5)
```

**Comment by ottyn** [comment]
I get the same error on the user side.  Nothing shows up on the GM side console.  Settings do not push to the player side.

Foundry 11.302, PF2e 5.0.2, Player Settings 11.01

![image](https://github.com/ironmonk88/monks-player-settings/assets/97130150/e0cb4f86-0aaf-4930-b743-83f201725d96)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
