### ISSUE TITLE
[BUG] Setting PF2E Dorako UI Not Saving

### ISSUE THREAD

**Issue by xKillerbees** [ironmonk88/monks-player-settings#22]
**Describe the bug**
When making adjustments for [All] or an individual player, settings changed within the module are not saved and reset to default

**To Reproduce**
1. Go to 'Configure Settings'
2. Click on 'All in view settings for player'
3. Scroll down to 'PF2e Dorako UI'
4. Change Chat Message header theme to Player Color
5. Save Changes
6. Log out and back in, check settings, will show disabled again
7. Can also check the player, settings will sync but that setting will not sync

**Expected behavior**
The settings I update within PF2E Dorako to update as I set defaults and it maintains them

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 11.315
 - System Pathfinder 2e
 - Module version - Monks - 11.04, Dorako UI 3.3.0, Dorako UX 1.2.0
 - Are there any errors in the console
 -
![image](https://github.com/ironmonk88/monks-player-settings/assets/2941079/5cff0f2a-9d91-4cc0-9ac5-2cb862a24a84)

**Comment by MrZeyami** [comment]
Confirming that Dorako UI and Doraku UX do not work with Sync Settings. They only save locally and do not update.

**Comment by Truncated** [comment]
I connected with a PC while having the same issue with Doraku UX - found that the player was getting this error when All Players configuration was being saved in the GM settings:

```
commons.js:2572 Uncaught (in promise) TypeError: Cannot create property 'no-cards' on string '[object Object]'
    at setProperty (commons.js:2572:19)
    at _expand (commons.js:2337:9)
    at expandObject (commons.js:2341:12)
    at MonksPlayerSettings.checkSettings (monks-player-settings.js:229:63)
    at MonksPlayerSettings.ready (monks-player-settings.js:57:29)
    at Object.fn (monks-player-settings.js:384:25)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8746:11)
    at async Game._initializeGameView (foundry.js:9990:5)
    at async Game.initialize (foundry.js:8650:5)
```
I assume it's getting hung up on the Hide Cards Tab setting?
I've found this typeError on a few other modules so far.

This is still in v11 for me, though.

**Comment by Truncated** [comment]
It looks like this problem is coming up with multiple add-ons for different settings where maybe the type parsing is off?
Basically I've found multiple modules that it doesn't record / sync settings and all them have different property names (i.e. no-cards in this example) but the problem is that they are all saying that they cannot create property on string `[object Object]`

It took me a hot minute to notice that the property name sometimes was different after I made this bug. I'll try to collect some more of the errors and their source module names for additional reference.

From what I'm seeing, it seems like the problem is where some modules have this type of setting that isn't correctly handled so hopefully it's one bug fix for all the modules rather than a module-specific issue as I thought it was originally.
